//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_type")]
pub enum OrderType {
    #[sea_orm(string_value = "limit")]
    Limit,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "stop_limit")]
    StopLimit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "side")]
pub enum Side {
    #[sea_orm(string_value = "buy")]
    Buy,
    #[sea_orm(string_value = "sell")]
    Sell,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "strategy_status"
)]
pub enum StrategyStatus {
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "triggered")]
    Triggered,
    #[sea_orm(string_value = "stopped")]
    Stopped,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "queued")]
    Queued,
}
