//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::OrderType;
use super::sea_orm_active_enums::Side;
use super::sea_orm_active_enums::StrategyStatus;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "strategy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub symbol: String,
    pub side: Side,
    pub order_type: OrderType,
    pub leverage: i32,
    pub price: Decimal,
    pub quantity: Decimal,
    pub status: StrategyStatus,
    #[sea_orm(column_type = "Text")]
    pub condition: String,
    pub stop_loss_pct: Option<Decimal>,
    pub stop_loss_price: Option<Decimal>,
    pub scheduled_at: Option<DateTimeWithTimeZone>,
    pub executed_at: Option<DateTimeWithTimeZone>,
    pub queued_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}